#!/bin/sh

set -eu

ARCHIVE_AREAS="main contrib non-free-firmware"

lb config noauto \
	-a amd64 \
	-d bookworm \
	--archive-areas "$ARCHIVE_AREAS" \
	--iso-application "DeltaSTEP Live" \
	--iso-publisher "DeltaSTEP Project" \
	--bootappend-live "boot=live components hostname=deltastep" \
	--debian-installer live \
	--image-name "DeltaSTEP" \
	"$@"

mkdir -p config/hooks
cp config/hooks.*/* config/hooks
